Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "Mosmena command guide"
Write-Host "====================="
Write-Host ""
Write-Host "1. Check prerequisites"
Write-Host "   .\scripts\doctor.ps1"
Write-Host ""
Write-Host "2. Prepare local configuration"
Write-Host "   .\scripts\setup.ps1"
Write-Host ""
Write-Host "3. Build the Android app"
Write-Host "   .\scripts\build.ps1"
Write-Host ""
Write-Host "4. Run the app on a connected device or emulator"
Write-Host "   .\scripts\run-android.ps1"
Write-Host ""
Write-Host "5. Run unit tests"
Write-Host "   .\scripts\test.ps1"
Write-Host ""
Write-Host "6. Run the main quality suite"
Write-Host "   .\scripts\quality.ps1"
Write-Host ""
Write-Host "7. Build or serve docs"
Write-Host "   .\scripts\docs.ps1"
Write-Host "   .\scripts\docs.ps1 -Serve"
Write-Host ""
Write-Host "8. Run the local wiki"
Write-Host "   .\scripts\wiki.ps1 -Detached"
